### ISSUE TITLE
compilation errors referring to SDL2

### ISSUE THREAD

**Issue by Softsapiens** [helsinki-frp/yampy-cube#1]
Hi,
I can't compile due to compilation errors referring to SDL2.
I follow your building instructions and install sdl2.0.0 but appears:

src/Input.hs:97:41:
                                                                                                               │    Not in scope: data constructor ‘SDL.KeyPressed’
                                                                                                               │    Perhaps you meant ‘SDL.Pressed’ (imported from SDL)
                                                                                                               │
                                                                                                               │src/Input.hs:99:41:
                                                                                                               │    Not in scope: data constructor ‘SDL.KeyReleased’
                                                                                                               │    Perhaps you meant ‘SDL.Released’ (imported from SDL)
                                                                                                               │
                                                                                                               │src/Input.hs:107:16:
                                                                                                               │    Not in scope: data constructor ‘SDL.MouseButtonUp’
                                                                                                               │
                                                                                                               │src/Input.hs:108:16:
                                                                                                               │    Not in scope: data constructor ‘SDL.MouseButtonDown’
                                                                                                               │    Perhaps you meant ‘SDL.MouseButtonEvent’ (imported from SDL)
                                                                                                               │
                                                                                                               │src/Input.hs:109:16:
                                                                                                               │    Not in scope: data constructor ‘SDL.MouseButtonUp’
                                                                                                               │
                                                                                                               │src/Input.hs:110:16:
                                                                                                               │    Not in scope: data constructor ‘SDL.MouseButtonDown’
                                                                                                               │    Perhaps you meant ‘SDL.MouseButtonEvent’ (imported from SDL)
                                                                                                               │cabal: Error: some packages failed to install:
                                                                                                               │yampa-demos-template-0.1.0.0 failed during the building phase.

I appreciate your help,
Dani

**Comment by zudov** [comment]
Hi, it looks like `sdl2` changed the api.

As an immediate solution, try to use commit `4217712` when building `sdl2`. (just do `git checkout 4217712` after cloning `sdl2`).

I'll take a closer look now and will fix it properly.

**Comment by zudov** [comment]
@Softsapiens I've patched the code and updated the build process. It now uses `stack` and it should be much easier to get running. See the updated instructions in `README.md`.

Thanks for reporting this. Tell me if it still doesn't work for you.

**Comment by zudov** [comment]
Closing it now, please reopen if you still have issues.

**Comment by Softsapiens** [comment]
Thank you very much,
and sorry for the delay!

I'll try again...
